In [1]:
!pip install numpy

In [1]:
import numpy as np
lst=[1,2,3,4]
type(lst)

list

In [5]:
a=np.array(lst)     #typecasting

In [6]:
type(a)

numpy.ndarray

In [7]:
a.shape       # (x,) --> means single dimention(1d arrey)

(4,)

In [8]:
nested_list=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
b=np.array(nested_list)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
b.shape    #(rows,column)

(4, 3)

In [10]:
b.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [11]:
b.reshape(2,7)  #error

ValueError: cannot reshape array of size 12 into shape (2,7)

In [12]:
b.reshape(1,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [13]:
b.reshape(2,2,3)     # 2 rows of 2*3 matrix

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
a.shape

(4,)

In [15]:
a.reshape(1,4)

array([[1, 2, 3, 4]])

In [16]:
a.reshape(1,4).shape

(1, 4)

In [17]:
np.array(["vbhvh", 2, 3])      # U5 means unicde string

array(['vbhvh', '2', '3'], dtype='<U5')

In [18]:
type(np.array(["vbhvh", 2, 3]))

numpy.ndarray

In [19]:
np.array([1, 2, 3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [20]:
 np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [21]:
 np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [22]:
#Data-type consisting of more than one element:

In [23]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])     # i2(8*2=16 bit)   ... i2 is data type.
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [33]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
b[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [37]:
b[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [38]:
b[1:3,[0,2]]

array([[4, 6],
       [7, 9]])

In [65]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [69]:
b[(0,3),[0,2]]

array([ 1, 12])

# Creating an array from sub-classes:

In [70]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [77]:
issubclass(np.matrix,np.ndarray)

True

In [2]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [6]:
np.mat([[1,2],[3,4,5]])

matrix([[list([1, 2]), list([3, 4, 5])]], dtype=object)

# numpy.asarray

In [79]:
#Convert the input to an array.

In [7]:
#Convert a list into an array:

In [8]:
 a = [1, 2]
type(a)

list

In [10]:
type(np.asarray(a))    #parameters are little bit different from array. 

numpy.ndarray

In [14]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [12]:
issubclass(np.matrix, np.ndarray)   # matrix is a subclass of array

True

In [16]:
issubclass( np.ndarray, np.matrix)

False

In [20]:
a = [1, 2]
np.asanyarray(a)    # if data is not any form of array then it will change to array 
                    # and if data is in form of any array then it will not change

array([1, 2])

In [22]:
a = np.matrix([[1, 2]])
np.asanyarray(a)        # since matrix is a form of array then it will not change type(matrix is subclass of array)

matrix([[1, 2]])

In [24]:
np.array(a)        # array function change matrix to array

array([[1, 2]])

In [25]:
a = np.matrix([[1, 2]])
np.asanyarray(a)

matrix([[1, 2]])

In [27]:
np.asarray(a)      #it will also change matrix in array(but isanyarray dont change matrix in array)

array([[1, 2]])

In [28]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [29]:
y=x      #Shallow copy

In [30]:
y

array([1, 2, 3])

In [42]:
y[1]=3293
y

array([   1, 3293,    3])

In [35]:
x    #changes  in y also result change in x and vice-versa.

array([   1, 3293,    3])

In [37]:
z=np.copy(x)      #Deep copy
x

array([   1, 3293,    3])

In [38]:
z

array([   1, 3293,    3])

In [40]:
z[0]=89
z

array([  89, 3293,    3])

In [41]:
x     # bcoz we use copy so changes in z don't change x


array([   1, 3293,    3])

# numpy.fromfunction

In [78]:
np.fromfunction(lambda i,j: i==j, (3,3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [90]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [94]:
np.fromfunction(lambda i, j, k: i * j* k, (3, 3,3), dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [95]:
#Create a new 1-dimensional array from an iterable object.

In [96]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x0000014A14053200>

In [97]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [98]:
#A new 1-D array initialized from text data in a string

In [99]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [100]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

In [101]:
# How to create create a record array from a (flat) list of arrays

In [102]:
x1=np.array([1,2,3,4])

In [103]:
x2=np.array(['a','dd','xyz','12'])

In [104]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [105]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [109]:
r[1]["b"]

'dd'

# data types

In [110]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [112]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [120]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [123]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)


We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [115]:
list(range(4,7))

[4, 5, 6]

In [125]:
list(range(4,50,5))

[4, 9, 14, 19, 24, 29, 34, 39, 44, 49]

In [127]:
list(range(4.5,50,5))   # error (we don't use float)

TypeError: 'float' object cannot be interpreted as an integer

In [128]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [129]:
list(range(50,-1,5))

[]

In [136]:
np.arange(5.6,50,3.9)    #arange handle float values (that is difference b/w range and arange)

array([ 5.6,  9.5, 13.4, 17.3, 21.2, 25.1, 29. , 32.9, 36.8, 40.7, 44.6,
       48.5])

In [139]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [140]:
np.linspace(1,5,10,endpoint=False)     #not include 5

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6])

In [135]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))    #(start,stop,no. of data)

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


# Matrix creation

In [143]:

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [144]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [147]:
np.zeros((3,4))   # Notice Tuples

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [148]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [150]:
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples

                        # we have 2*8 array 5 times

[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [156]:
(5+np.ones((3,5)))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [158]:
np.ones((3,5)) * 10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [174]:
np.empty((3,5))

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [175]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [176]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [177]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [179]:
np.linspace(2.0, 3.0, num=9, retstep=True)    # difference b/w 2 numbers is also here

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [180]:
#Return numbers spaced evenly on a log scale.

In [181]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [182]:
np.log10(2)

0.3010299956639812

In [183]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [2]:
a=np.array(np.zeros((4,5,2)))
print(a.shape)
print(a.size)
print(a.ndim)

(4, 5, 2)
40
3


In [3]:
a=9
np.array(a).ndim      # that means this is scaler data (0 dimension means scaler)

0

In [4]:
np.array([3,4,5]).ndim   # vector data

1

In [15]:
#Extract a diagonal or construct a diagonal array.

In [18]:
np.arange(16).reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [21]:
np.arange(16).reshape(2,-1)      # ( -1 means data automatically finds for what we have to multiply)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [22]:
x = np.arange(16).reshape((-1,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
x.shape

(4, 4)

In [34]:
np.arange(8).reshape(-1,2)   #  -1 is very important

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [35]:
np.arange(16).reshape(2,2,-1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [32]:
x.diagonal()

array([ 0,  5, 10, 15])

In [41]:
np.diag(x)

array([ 0,  5, 10, 15])

In [47]:
# if we dont have square matrix then
a=np.arange(16).reshape(2,8)
print(a)
np.diag(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


array([0, 9])

In [49]:
np.diag(a, k=4)

array([ 4, 13])

In [50]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
np.diag(x, k=0)

array([ 0,  5, 10, 15])

In [54]:
np.diag(x, k=1)   #diag of matrix after leaving 1 index

array([ 1,  6, 11])

In [55]:
np.diag(x, k=2)    # leave 2 index and take square matrix

array([2, 7])

In [56]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [57]:
np.diag(x, k=-2)

array([ 8, 13])

In [59]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [60]:
np.diag(a,k=3)

array([ 3, 12])

In [61]:
np.diag(a,k=-1)

array([8])

In [66]:
np.diag(np.diag(np.arange(16).reshape(-1,4)))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [67]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [69]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [71]:
np.diagflat([[1,2], [3,4]])     # first flat the list([1,2,3,4]) and then diag

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [78]:
np.diagflat([[1,2], [3,4]],k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [79]:
np.diagflat([[1,2], [3,4]],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [77]:
np.diagflat([1,2],k=1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [ ]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [85]:
np.tri(3, 3, 0, dtype=int)      #(row,column,k)

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

In [89]:
np.tri(3, 3, 1, dtype=int)

array([[1, 1, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [90]:
np.tri(3, 3, 2, dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [82]:
np.tri(3, 5, 0, dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [80]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [91]:
np.tri(3, 5, 2, dtype=int)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [94]:
m=np.tri(5, 5, 1, dtype=int)
m

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [96]:
#for i in m:
#    for j in i:
#        print(j)

In [97]:
#return a Lower triangle of an array.

In [104]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [105]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 1)     # here k = 1

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
#return Upper triangle of an array.

In [106]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

In [107]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

In [108]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

# Random number generation

In [113]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.72924479 0.35642971 0.5376912 ]
 [0.56790022 0.65391234 0.90240277]]


In [111]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.66614954 -0.26036161 -0.10591999]
 [-2.26573076 -0.48785907  0.09877462]
 [-0.01012386  0.53377158 -1.3282987 ]
 [-0.50339683  0.4656079  -0.49511081]]


In [119]:
np.random.randn(2,2,2)

array([[[-0.86429321, -0.96549829],
        [ 0.45113636, -0.33404079]],

       [[ 0.01702948,  1.46013226],
        [ 0.05253217,  0.67008561]]])

In [120]:
np.random.randint(1,10) #randint (low, high, # of samples to be drawn)

4

In [229]:
np.random.randint(1,100,(5,5))

array([[82, 39, 93, 70, 81],
       [ 7, 52, 77, 86, 74],
       [33, 79, 84, 37, 29],
       [41, 94, 56,  3, 25],
       [49, 75, 53, 71, 77]])

# Reshaping

In [134]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
print(" a is \n {}: \n ".format(a))
print("b is :\n  {} \n".format(b))
print("c is :\n  {} \n".format(c))

 a is 
 [38 74 91 41 19 54  1 26 99 74 24 67 68 19 55 58 55 58 31 71 83 13 26 38
 31 69 90  1 59  1]: 
 
b is :
  [[[38 74 91 41 19]
  [54  1 26 99 74]
  [24 67 68 19 55]]

 [[58 55 58 31 71]
  [83 13 26 38 31]
  [69 90  1 59  1]]] 

c is :
  [[38 74 91 41 19]
 [54  1 26 99 74]
 [24 67 68 19 55]
 [58 55 58 31 71]
 [83 13 26 38 31]
 [69 90  1 59  1]] 



In [135]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [136]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))


Vector of random integers
 -------------------------------------------------- 
 [97 16 27 93 19 10 75 34 13 38]

Here is the sorted vector
 -------------------------------------------------- 
 [10 13 16 19 27 34 38 75 93 97]


In [139]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
M

array([[93, 42, 25, 71, 19],
       [ 2, 43, 43, 80, 61],
       [72, 63, 62, 59, 20],
       [13, 80, 51, 76,  3],
       [ 6, 73, 39, 37, 28]])

In [140]:
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1


Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[19 25 42 71 93]
 [ 2 43 43 61 80]
 [20 59 62 63 72]
 [ 3 13 51 76 80]
 [ 6 28 37 39 73]]


In [142]:
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 2 42 25 37  3]
 [ 6 43 39 59 19]
 [13 63 43 71 20]
 [72 73 51 76 28]
 [93 80 62 80 61]]


In [143]:
# we have to see weather our data shifts along row axis or column axis

In [144]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

Max of a: 93
Max of b: 99


array([[[38, 74, 91, 41, 19],
        [54,  1, 26, 99, 74],
        [24, 67, 68, 19, 55]],

       [[58, 55, 58, 31, 71],
        [83, 13, 26, 38, 31],
        [69, 90,  1, 59,  1]]])

In [147]:
M

array([[93, 42, 25, 71, 19],
       [ 2, 43, 43, 80, 61],
       [72, 63, 62, 59, 20],
       [13, 80, 51, 76,  3],
       [ 6, 73, 39, 37, 28]])

In [154]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmin())    # flatten data and give us maximum
print("Max of c location:", c.argmax())

Max of a location: [0 3 0 1 1]
Max of b location: 6
Max of c location: 8


In [158]:
b.max()

99

In [159]:
b.argmax()

8

# Indexing and slicing

In [151]:
arr = np.arange(0,11)
print("Array:",arr)

Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [152]:
arr[7]

7

In [153]:
arr[3:6:2]

array([3, 5])

In [160]:
arr[:4]

array([0, 1, 2, 3])

In [161]:
arr[-1:7:-1]

array([10,  9,  8])

In [162]:
 arr[-1:-6:2]

array([], dtype=int32)

In [168]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print(mat)
print("\n--------------------------------\n", mat[1:4,3:5])
print("\n--------------------------------\n",mat[0:3,[1,3]])

[[30 37 52 18 35]
 [85 20 77 11 56]
 [56 90 39 94 88]]

--------------------------------
 [[11 56]
 [94 88]]

--------------------------------
 [[37 18]
 [20 11]
 [90 94]]


In [170]:
mat = np.array(ri(10,100,45)).reshape(3,5,3)
mat

array([[[81, 18, 69],
        [26, 76, 71],
        [53, 19, 34],
        [67, 17, 39],
        [87, 28, 69]],

       [[11, 18, 29],
        [57, 84, 12],
        [44, 46, 68],
        [52, 27, 98],
        [14, 29, 75]],

       [[24, 12, 52],
        [37, 69, 11],
        [72, 73, 90],
        [23, 22, 72],
        [17, 49, 96]]])

In [171]:
mat[1][1]

array([57, 84, 12])

In [173]:
mat[0][:,1]

array([18, 76, 19, 17, 28])

In [191]:
for i in mat:      # first 2 rows of each 3 matrix in mat.
    print(i[0:2,:])

[[81 18 69]
 [26 76 71]]
[[11 18 29]
 [57 84 12]]
[[24 12 52]
 [37 69 11]]


In [192]:
# or 

In [193]:
mat[0:3,[0,1]]

array([[[81, 18, 69],
        [26, 76, 71]],

       [[11, 18, 29],
        [57, 84, 12]],

       [[24, 12, 52],
        [37, 69, 11]]])

# Subseting

In [195]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print(mat)
mat>50

[[22 25 26 55 67]
 [77 67 96 46 60]
 [94 35 15 41 43]]


array([[False, False, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True, False, False, False, False]])

In [196]:
mat[mat>50]

array([55, 67, 77, 67, 96, 60, 94])

# Universal Functions

In [198]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print(mat1)
print("*" * 50)
print(mat2)

[[6 4 4]
 [3 4 3]
 [7 6 8]]
**************************************************
[[7 4 1]
 [9 9 4]
 [6 3 6]]


In [199]:
mat1*mat2   # index wise multiplication

array([[42, 16,  4],
       [27, 36, 12],
       [42, 18, 48]])

In [200]:
mat1@mat2    #real matrix multiplication

array([[102,  72,  46],
       [ 75,  57,  37],
       [151, 106,  79]])

In [201]:
100+mat1

array([[106, 104, 104],
       [103, 104, 103],
       [107, 106, 108]])

In [202]:
mat1**3

array([[216,  64,  64],
       [ 27,  64,  27],
       [343, 216, 512]], dtype=int32)

In [203]:
pow(mat1,3)

array([[216,  64,  64],
       [ 27,  64,  27],
       [343, 216, 512]], dtype=int32)

# Broadcasting

In [204]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [205]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [206]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [207]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T       #transpose
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [208]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [209]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [210]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)


1st Matrix of random single-digit numbers

 [[9 4 4]
 [9 7 4]
 [9 6 1]]

2nd Matrix of random single-digit numbers
------------
 [[7 1 3]
 [5 2 3]
 [2 3 9]]


In [217]:
 np.sqrt(mat1)

array([[3.        , 2.        , 2.        ],
       [3.        , 2.64575131, 2.        ],
       [3.        , 2.44948974, 1.        ]])

In [218]:
np.exp(mat1)

array([[8.10308393e+03, 5.45981500e+01, 5.45981500e+01],
       [8.10308393e+03, 1.09663316e+03, 5.45981500e+01],
       [8.10308393e+03, 4.03428793e+02, 2.71828183e+00]])

In [224]:
np.log10(mat1)

array([[0.95424251, 0.60205999, 0.60205999],
       [0.95424251, 0.84509804, 0.60205999],
       [0.95424251, 0.77815125, 0.        ]])

In [225]:
mat1%mat2

array([[2, 0, 1],
       [4, 1, 1],
       [1, 0, 1]], dtype=int32)

In [227]:
 np.fmod(mat1,mat2)    # modulus only

array([[2, 0, 1],
       [4, 1, 1],
       [1, 0, 1]], dtype=int32)

In [228]:
A = np.linspace(0,12*np.pi,1001)
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])